//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demonstration.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://microsoft.com/webservices/", ConfigurationName="ServiceReference1.Service1Soap")]
    public interface Service1Soap {
        
        // CODEGEN: Generating message contract since element name Email from namespace http://microsoft.com/webservices/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/webservices/getSequences_runZooPhy", ReplyAction="*")]
        Demonstration.ServiceReference1.getSequences_runZooPhyResponse getSequences_runZooPhy(Demonstration.ServiceReference1.getSequences_runZooPhyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/webservices/getSequences_runZooPhy", ReplyAction="*")]
        System.Threading.Tasks.Task<Demonstration.ServiceReference1.getSequences_runZooPhyResponse> getSequences_runZooPhyAsync(Demonstration.ServiceReference1.getSequences_runZooPhyRequest request);
        
        // CODEGEN: Generating message contract since element name disease from namespace http://microsoft.com/webservices/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/webservices/getSequences_Unaligned", ReplyAction="*")]
        Demonstration.ServiceReference1.getSequences_UnalignedResponse getSequences_Unaligned(Demonstration.ServiceReference1.getSequences_UnalignedRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/webservices/getSequences_Unaligned", ReplyAction="*")]
        System.Threading.Tasks.Task<Demonstration.ServiceReference1.getSequences_UnalignedResponse> getSequences_UnalignedAsync(Demonstration.ServiceReference1.getSequences_UnalignedRequest request);
        
        // CODEGEN: Generating message contract since element name disease from namespace http://microsoft.com/webservices/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/webservices/getGeoSequences_Unaligned", ReplyAction="*")]
        Demonstration.ServiceReference1.getGeoSequences_UnalignedResponse getGeoSequences_Unaligned(Demonstration.ServiceReference1.getGeoSequences_UnalignedRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/webservices/getGeoSequences_Unaligned", ReplyAction="*")]
        System.Threading.Tasks.Task<Demonstration.ServiceReference1.getGeoSequences_UnalignedResponse> getGeoSequences_UnalignedAsync(Demonstration.ServiceReference1.getGeoSequences_UnalignedRequest request);
        
        // CODEGEN: Generating message contract since element name hosts from namespace http://microsoft.com/webservices/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/webservices/getDescendantA", ReplyAction="*")]
        Demonstration.ServiceReference1.getDescendantAResponse getDescendantA(Demonstration.ServiceReference1.getDescendantARequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/webservices/getDescendantA", ReplyAction="*")]
        System.Threading.Tasks.Task<Demonstration.ServiceReference1.getDescendantAResponse> getDescendantAAsync(Demonstration.ServiceReference1.getDescendantARequest request);
        
        // CODEGEN: Generating message contract since element name hosts from namespace http://microsoft.com/webservices/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/webservices/getDescendant", ReplyAction="*")]
        Demonstration.ServiceReference1.getDescendantResponse getDescendant(Demonstration.ServiceReference1.getDescendantRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/webservices/getDescendant", ReplyAction="*")]
        System.Threading.Tasks.Task<Demonstration.ServiceReference1.getDescendantResponse> getDescendantAsync(Demonstration.ServiceReference1.getDescendantRequest request);
        
        // CODEGEN: Generating message contract since element name locs from namespace http://microsoft.com/webservices/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/webservices/getLocation", ReplyAction="*")]
        Demonstration.ServiceReference1.getLocationResponse getLocation(Demonstration.ServiceReference1.getLocationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/webservices/getLocation", ReplyAction="*")]
        System.Threading.Tasks.Task<Demonstration.ServiceReference1.getLocationResponse> getLocationAsync(Demonstration.ServiceReference1.getLocationRequest request);
        
        // CODEGEN: Generating message contract since element name Email from namespace http://microsoft.com/webservices/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/webservices/runBeast_", ReplyAction="*")]
        Demonstration.ServiceReference1.runBeast_Response runBeast_(Demonstration.ServiceReference1.runBeast_Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/webservices/runBeast_", ReplyAction="*")]
        System.Threading.Tasks.Task<Demonstration.ServiceReference1.runBeast_Response> runBeast_Async(Demonstration.ServiceReference1.runBeast_Request request);
        
        // CODEGEN: Generating message contract since element name JobId from namespace http://microsoft.com/webservices/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/webservices/LogComp", ReplyAction="*")]
        Demonstration.ServiceReference1.LogCompResponse LogComp(Demonstration.ServiceReference1.LogCompRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/webservices/LogComp", ReplyAction="*")]
        System.Threading.Tasks.Task<Demonstration.ServiceReference1.LogCompResponse> LogCompAsync(Demonstration.ServiceReference1.LogCompRequest request);
        
        // CODEGEN: Generating message contract since element name Email from namespace http://microsoft.com/webservices/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/webservices/ownSequences_runZooPhy", ReplyAction="*")]
        Demonstration.ServiceReference1.ownSequences_runZooPhyResponse ownSequences_runZooPhy(Demonstration.ServiceReference1.ownSequences_runZooPhyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/webservices/ownSequences_runZooPhy", ReplyAction="*")]
        System.Threading.Tasks.Task<Demonstration.ServiceReference1.ownSequences_runZooPhyResponse> ownSequences_runZooPhyAsync(Demonstration.ServiceReference1.ownSequences_runZooPhyRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getSequences_runZooPhyRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getSequences_runZooPhy", Namespace="http://microsoft.com/webservices/", Order=0)]
        public Demonstration.ServiceReference1.getSequences_runZooPhyRequestBody Body;
        
        public getSequences_runZooPhyRequest() {
        }
        
        public getSequences_runZooPhyRequest(Demonstration.ServiceReference1.getSequences_runZooPhyRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://microsoft.com/webservices/")]
    public partial class getSequences_runZooPhyRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Email;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string disease;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string region;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string hosts;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string gene;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string StartEnd;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string sModel;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string UserSpcdId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string mcmc;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string sampleFreq;
        
        public getSequences_runZooPhyRequestBody() {
        }
        
        public getSequences_runZooPhyRequestBody(string Email, string disease, string region, string hosts, string gene, string StartEnd, string sModel, string UserSpcdId, string mcmc, string sampleFreq) {
            this.Email = Email;
            this.disease = disease;
            this.region = region;
            this.hosts = hosts;
            this.gene = gene;
            this.StartEnd = StartEnd;
            this.sModel = sModel;
            this.UserSpcdId = UserSpcdId;
            this.mcmc = mcmc;
            this.sampleFreq = sampleFreq;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getSequences_runZooPhyResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getSequences_runZooPhyResponse", Namespace="http://microsoft.com/webservices/", Order=0)]
        public Demonstration.ServiceReference1.getSequences_runZooPhyResponseBody Body;
        
        public getSequences_runZooPhyResponse() {
        }
        
        public getSequences_runZooPhyResponse(Demonstration.ServiceReference1.getSequences_runZooPhyResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class getSequences_runZooPhyResponseBody {
        
        public getSequences_runZooPhyResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getSequences_UnalignedRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getSequences_Unaligned", Namespace="http://microsoft.com/webservices/", Order=0)]
        public Demonstration.ServiceReference1.getSequences_UnalignedRequestBody Body;
        
        public getSequences_UnalignedRequest() {
        }
        
        public getSequences_UnalignedRequest(Demonstration.ServiceReference1.getSequences_UnalignedRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://microsoft.com/webservices/")]
    public partial class getSequences_UnalignedRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string disease;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string region;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string hosts;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string gene;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string StartEnd;
        
        public getSequences_UnalignedRequestBody() {
        }
        
        public getSequences_UnalignedRequestBody(string disease, string region, string hosts, string gene, string StartEnd) {
            this.disease = disease;
            this.region = region;
            this.hosts = hosts;
            this.gene = gene;
            this.StartEnd = StartEnd;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getSequences_UnalignedResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getSequences_UnalignedResponse", Namespace="http://microsoft.com/webservices/", Order=0)]
        public Demonstration.ServiceReference1.getSequences_UnalignedResponseBody Body;
        
        public getSequences_UnalignedResponse() {
        }
        
        public getSequences_UnalignedResponse(Demonstration.ServiceReference1.getSequences_UnalignedResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://microsoft.com/webservices/")]
    public partial class getSequences_UnalignedResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getSequences_UnalignedResult;
        
        public getSequences_UnalignedResponseBody() {
        }
        
        public getSequences_UnalignedResponseBody(string getSequences_UnalignedResult) {
            this.getSequences_UnalignedResult = getSequences_UnalignedResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getGeoSequences_UnalignedRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getGeoSequences_Unaligned", Namespace="http://microsoft.com/webservices/", Order=0)]
        public Demonstration.ServiceReference1.getGeoSequences_UnalignedRequestBody Body;
        
        public getGeoSequences_UnalignedRequest() {
        }
        
        public getGeoSequences_UnalignedRequest(Demonstration.ServiceReference1.getGeoSequences_UnalignedRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://microsoft.com/webservices/")]
    public partial class getGeoSequences_UnalignedRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string disease;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string region;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string hosts;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string gene;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string StartEnd;
        
        public getGeoSequences_UnalignedRequestBody() {
        }
        
        public getGeoSequences_UnalignedRequestBody(string disease, string region, string hosts, string gene, string StartEnd) {
            this.disease = disease;
            this.region = region;
            this.hosts = hosts;
            this.gene = gene;
            this.StartEnd = StartEnd;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getGeoSequences_UnalignedResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getGeoSequences_UnalignedResponse", Namespace="http://microsoft.com/webservices/", Order=0)]
        public Demonstration.ServiceReference1.getGeoSequences_UnalignedResponseBody Body;
        
        public getGeoSequences_UnalignedResponse() {
        }
        
        public getGeoSequences_UnalignedResponse(Demonstration.ServiceReference1.getGeoSequences_UnalignedResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://microsoft.com/webservices/")]
    public partial class getGeoSequences_UnalignedResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getGeoSequences_UnalignedResult;
        
        public getGeoSequences_UnalignedResponseBody() {
        }
        
        public getGeoSequences_UnalignedResponseBody(string getGeoSequences_UnalignedResult) {
            this.getGeoSequences_UnalignedResult = getGeoSequences_UnalignedResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getDescendantARequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getDescendantA", Namespace="http://microsoft.com/webservices/", Order=0)]
        public Demonstration.ServiceReference1.getDescendantARequestBody Body;
        
        public getDescendantARequest() {
        }
        
        public getDescendantARequest(Demonstration.ServiceReference1.getDescendantARequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://microsoft.com/webservices/")]
    public partial class getDescendantARequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string hosts;
        
        public getDescendantARequestBody() {
        }
        
        public getDescendantARequestBody(string hosts) {
            this.hosts = hosts;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getDescendantAResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getDescendantAResponse", Namespace="http://microsoft.com/webservices/", Order=0)]
        public Demonstration.ServiceReference1.getDescendantAResponseBody Body;
        
        public getDescendantAResponse() {
        }
        
        public getDescendantAResponse(Demonstration.ServiceReference1.getDescendantAResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://microsoft.com/webservices/")]
    public partial class getDescendantAResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getDescendantAResult;
        
        public getDescendantAResponseBody() {
        }
        
        public getDescendantAResponseBody(string getDescendantAResult) {
            this.getDescendantAResult = getDescendantAResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getDescendantRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getDescendant", Namespace="http://microsoft.com/webservices/", Order=0)]
        public Demonstration.ServiceReference1.getDescendantRequestBody Body;
        
        public getDescendantRequest() {
        }
        
        public getDescendantRequest(Demonstration.ServiceReference1.getDescendantRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://microsoft.com/webservices/")]
    public partial class getDescendantRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string hosts;
        
        public getDescendantRequestBody() {
        }
        
        public getDescendantRequestBody(string hosts) {
            this.hosts = hosts;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getDescendantResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getDescendantResponse", Namespace="http://microsoft.com/webservices/", Order=0)]
        public Demonstration.ServiceReference1.getDescendantResponseBody Body;
        
        public getDescendantResponse() {
        }
        
        public getDescendantResponse(Demonstration.ServiceReference1.getDescendantResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://microsoft.com/webservices/")]
    public partial class getDescendantResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getDescendantResult;
        
        public getDescendantResponseBody() {
        }
        
        public getDescendantResponseBody(string getDescendantResult) {
            this.getDescendantResult = getDescendantResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getLocationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getLocation", Namespace="http://microsoft.com/webservices/", Order=0)]
        public Demonstration.ServiceReference1.getLocationRequestBody Body;
        
        public getLocationRequest() {
        }
        
        public getLocationRequest(Demonstration.ServiceReference1.getLocationRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://microsoft.com/webservices/")]
    public partial class getLocationRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string locs;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int intLoc;
        
        public getLocationRequestBody() {
        }
        
        public getLocationRequestBody(string locs, int intLoc) {
            this.locs = locs;
            this.intLoc = intLoc;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getLocationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getLocationResponse", Namespace="http://microsoft.com/webservices/", Order=0)]
        public Demonstration.ServiceReference1.getLocationResponseBody Body;
        
        public getLocationResponse() {
        }
        
        public getLocationResponse(Demonstration.ServiceReference1.getLocationResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://microsoft.com/webservices/")]
    public partial class getLocationResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getLocationResult;
        
        public getLocationResponseBody() {
        }
        
        public getLocationResponseBody(string getLocationResult) {
            this.getLocationResult = getLocationResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class runBeast_Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="runBeast_", Namespace="http://microsoft.com/webservices/", Order=0)]
        public Demonstration.ServiceReference1.runBeast_RequestBody Body;
        
        public runBeast_Request() {
        }
        
        public runBeast_Request(Demonstration.ServiceReference1.runBeast_RequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://microsoft.com/webservices/")]
    public partial class runBeast_RequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Email;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string newDir0;
        
        public runBeast_RequestBody() {
        }
        
        public runBeast_RequestBody(string Email, string newDir0) {
            this.Email = Email;
            this.newDir0 = newDir0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class runBeast_Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="runBeast_Response", Namespace="http://microsoft.com/webservices/", Order=0)]
        public Demonstration.ServiceReference1.runBeast_ResponseBody Body;
        
        public runBeast_Response() {
        }
        
        public runBeast_Response(Demonstration.ServiceReference1.runBeast_ResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://microsoft.com/webservices/")]
    public partial class runBeast_ResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string runBeast_Result;
        
        public runBeast_ResponseBody() {
        }
        
        public runBeast_ResponseBody(string runBeast_Result) {
            this.runBeast_Result = runBeast_Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LogCompRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LogComp", Namespace="http://microsoft.com/webservices/", Order=0)]
        public Demonstration.ServiceReference1.LogCompRequestBody Body;
        
        public LogCompRequest() {
        }
        
        public LogCompRequest(Demonstration.ServiceReference1.LogCompRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://microsoft.com/webservices/")]
    public partial class LogCompRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string JobId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string eMail;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Status;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string CompuType;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string SearchCR;
        
        public LogCompRequestBody() {
        }
        
        public LogCompRequestBody(string JobId, string eMail, string Status, string CompuType, string SearchCR) {
            this.JobId = JobId;
            this.eMail = eMail;
            this.Status = Status;
            this.CompuType = CompuType;
            this.SearchCR = SearchCR;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LogCompResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LogCompResponse", Namespace="http://microsoft.com/webservices/", Order=0)]
        public Demonstration.ServiceReference1.LogCompResponseBody Body;
        
        public LogCompResponse() {
        }
        
        public LogCompResponse(Demonstration.ServiceReference1.LogCompResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://microsoft.com/webservices/")]
    public partial class LogCompResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string LogCompResult;
        
        public LogCompResponseBody() {
        }
        
        public LogCompResponseBody(string LogCompResult) {
            this.LogCompResult = LogCompResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ownSequences_runZooPhyRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ownSequences_runZooPhy", Namespace="http://microsoft.com/webservices/", Order=0)]
        public Demonstration.ServiceReference1.ownSequences_runZooPhyRequestBody Body;
        
        public ownSequences_runZooPhyRequest() {
        }
        
        public ownSequences_runZooPhyRequest(Demonstration.ServiceReference1.ownSequences_runZooPhyRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://microsoft.com/webservices/")]
    public partial class ownSequences_runZooPhyRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Email;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string strInputFasta;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string sModel;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string UserSpcdId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string mcmc;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string logfr;
        
        public ownSequences_runZooPhyRequestBody() {
        }
        
        public ownSequences_runZooPhyRequestBody(string Email, string strInputFasta, string sModel, string UserSpcdId, string mcmc, string logfr) {
            this.Email = Email;
            this.strInputFasta = strInputFasta;
            this.sModel = sModel;
            this.UserSpcdId = UserSpcdId;
            this.mcmc = mcmc;
            this.logfr = logfr;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ownSequences_runZooPhyResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ownSequences_runZooPhyResponse", Namespace="http://microsoft.com/webservices/", Order=0)]
        public Demonstration.ServiceReference1.ownSequences_runZooPhyResponseBody Body;
        
        public ownSequences_runZooPhyResponse() {
        }
        
        public ownSequences_runZooPhyResponse(Demonstration.ServiceReference1.ownSequences_runZooPhyResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://microsoft.com/webservices/")]
    public partial class ownSequences_runZooPhyResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ownSequences_runZooPhyResult;
        
        public ownSequences_runZooPhyResponseBody() {
        }
        
        public ownSequences_runZooPhyResponseBody(string ownSequences_runZooPhyResult) {
            this.ownSequences_runZooPhyResult = ownSequences_runZooPhyResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Service1SoapChannel : Demonstration.ServiceReference1.Service1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1SoapClient : System.ServiceModel.ClientBase<Demonstration.ServiceReference1.Service1Soap>, Demonstration.ServiceReference1.Service1Soap {
        
        public Service1SoapClient() {
        }
        
        public Service1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Demonstration.ServiceReference1.getSequences_runZooPhyResponse Demonstration.ServiceReference1.Service1Soap.getSequences_runZooPhy(Demonstration.ServiceReference1.getSequences_runZooPhyRequest request) {
            return base.Channel.getSequences_runZooPhy(request);
        }
        
        public void getSequences_runZooPhy(string Email, string disease, string region, string hosts, string gene, string StartEnd, string sModel, string UserSpcdId, string mcmc, string sampleFreq) {
            Demonstration.ServiceReference1.getSequences_runZooPhyRequest inValue = new Demonstration.ServiceReference1.getSequences_runZooPhyRequest();
            inValue.Body = new Demonstration.ServiceReference1.getSequences_runZooPhyRequestBody();
            inValue.Body.Email = Email;
            inValue.Body.disease = disease;
            inValue.Body.region = region;
            inValue.Body.hosts = hosts;
            inValue.Body.gene = gene;
            inValue.Body.StartEnd = StartEnd;
            inValue.Body.sModel = sModel;
            inValue.Body.UserSpcdId = UserSpcdId;
            inValue.Body.mcmc = mcmc;
            inValue.Body.sampleFreq = sampleFreq;
            Demonstration.ServiceReference1.getSequences_runZooPhyResponse retVal = ((Demonstration.ServiceReference1.Service1Soap)(this)).getSequences_runZooPhy(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Demonstration.ServiceReference1.getSequences_runZooPhyResponse> Demonstration.ServiceReference1.Service1Soap.getSequences_runZooPhyAsync(Demonstration.ServiceReference1.getSequences_runZooPhyRequest request) {
            return base.Channel.getSequences_runZooPhyAsync(request);
        }
        
        public System.Threading.Tasks.Task<Demonstration.ServiceReference1.getSequences_runZooPhyResponse> getSequences_runZooPhyAsync(string Email, string disease, string region, string hosts, string gene, string StartEnd, string sModel, string UserSpcdId, string mcmc, string sampleFreq) {
            Demonstration.ServiceReference1.getSequences_runZooPhyRequest inValue = new Demonstration.ServiceReference1.getSequences_runZooPhyRequest();
            inValue.Body = new Demonstration.ServiceReference1.getSequences_runZooPhyRequestBody();
            inValue.Body.Email = Email;
            inValue.Body.disease = disease;
            inValue.Body.region = region;
            inValue.Body.hosts = hosts;
            inValue.Body.gene = gene;
            inValue.Body.StartEnd = StartEnd;
            inValue.Body.sModel = sModel;
            inValue.Body.UserSpcdId = UserSpcdId;
            inValue.Body.mcmc = mcmc;
            inValue.Body.sampleFreq = sampleFreq;
            return ((Demonstration.ServiceReference1.Service1Soap)(this)).getSequences_runZooPhyAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Demonstration.ServiceReference1.getSequences_UnalignedResponse Demonstration.ServiceReference1.Service1Soap.getSequences_Unaligned(Demonstration.ServiceReference1.getSequences_UnalignedRequest request) {
            return base.Channel.getSequences_Unaligned(request);
        }
        
        public string getSequences_Unaligned(string disease, string region, string hosts, string gene, string StartEnd) {
            Demonstration.ServiceReference1.getSequences_UnalignedRequest inValue = new Demonstration.ServiceReference1.getSequences_UnalignedRequest();
            inValue.Body = new Demonstration.ServiceReference1.getSequences_UnalignedRequestBody();
            inValue.Body.disease = disease;
            inValue.Body.region = region;
            inValue.Body.hosts = hosts;
            inValue.Body.gene = gene;
            inValue.Body.StartEnd = StartEnd;
            Demonstration.ServiceReference1.getSequences_UnalignedResponse retVal = ((Demonstration.ServiceReference1.Service1Soap)(this)).getSequences_Unaligned(inValue);
            return retVal.Body.getSequences_UnalignedResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Demonstration.ServiceReference1.getSequences_UnalignedResponse> Demonstration.ServiceReference1.Service1Soap.getSequences_UnalignedAsync(Demonstration.ServiceReference1.getSequences_UnalignedRequest request) {
            return base.Channel.getSequences_UnalignedAsync(request);
        }
        
        public System.Threading.Tasks.Task<Demonstration.ServiceReference1.getSequences_UnalignedResponse> getSequences_UnalignedAsync(string disease, string region, string hosts, string gene, string StartEnd) {
            Demonstration.ServiceReference1.getSequences_UnalignedRequest inValue = new Demonstration.ServiceReference1.getSequences_UnalignedRequest();
            inValue.Body = new Demonstration.ServiceReference1.getSequences_UnalignedRequestBody();
            inValue.Body.disease = disease;
            inValue.Body.region = region;
            inValue.Body.hosts = hosts;
            inValue.Body.gene = gene;
            inValue.Body.StartEnd = StartEnd;
            return ((Demonstration.ServiceReference1.Service1Soap)(this)).getSequences_UnalignedAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Demonstration.ServiceReference1.getGeoSequences_UnalignedResponse Demonstration.ServiceReference1.Service1Soap.getGeoSequences_Unaligned(Demonstration.ServiceReference1.getGeoSequences_UnalignedRequest request) {
            return base.Channel.getGeoSequences_Unaligned(request);
        }
        
        public string getGeoSequences_Unaligned(string disease, string region, string hosts, string gene, string StartEnd) {
            Demonstration.ServiceReference1.getGeoSequences_UnalignedRequest inValue = new Demonstration.ServiceReference1.getGeoSequences_UnalignedRequest();
            inValue.Body = new Demonstration.ServiceReference1.getGeoSequences_UnalignedRequestBody();
            inValue.Body.disease = disease;
            inValue.Body.region = region;
            inValue.Body.hosts = hosts;
            inValue.Body.gene = gene;
            inValue.Body.StartEnd = StartEnd;
            Demonstration.ServiceReference1.getGeoSequences_UnalignedResponse retVal = ((Demonstration.ServiceReference1.Service1Soap)(this)).getGeoSequences_Unaligned(inValue);
            return retVal.Body.getGeoSequences_UnalignedResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Demonstration.ServiceReference1.getGeoSequences_UnalignedResponse> Demonstration.ServiceReference1.Service1Soap.getGeoSequences_UnalignedAsync(Demonstration.ServiceReference1.getGeoSequences_UnalignedRequest request) {
            return base.Channel.getGeoSequences_UnalignedAsync(request);
        }
        
        public System.Threading.Tasks.Task<Demonstration.ServiceReference1.getGeoSequences_UnalignedResponse> getGeoSequences_UnalignedAsync(string disease, string region, string hosts, string gene, string StartEnd) {
            Demonstration.ServiceReference1.getGeoSequences_UnalignedRequest inValue = new Demonstration.ServiceReference1.getGeoSequences_UnalignedRequest();
            inValue.Body = new Demonstration.ServiceReference1.getGeoSequences_UnalignedRequestBody();
            inValue.Body.disease = disease;
            inValue.Body.region = region;
            inValue.Body.hosts = hosts;
            inValue.Body.gene = gene;
            inValue.Body.StartEnd = StartEnd;
            return ((Demonstration.ServiceReference1.Service1Soap)(this)).getGeoSequences_UnalignedAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Demonstration.ServiceReference1.getDescendantAResponse Demonstration.ServiceReference1.Service1Soap.getDescendantA(Demonstration.ServiceReference1.getDescendantARequest request) {
            return base.Channel.getDescendantA(request);
        }
        
        public string getDescendantA(string hosts) {
            Demonstration.ServiceReference1.getDescendantARequest inValue = new Demonstration.ServiceReference1.getDescendantARequest();
            inValue.Body = new Demonstration.ServiceReference1.getDescendantARequestBody();
            inValue.Body.hosts = hosts;
            Demonstration.ServiceReference1.getDescendantAResponse retVal = ((Demonstration.ServiceReference1.Service1Soap)(this)).getDescendantA(inValue);
            return retVal.Body.getDescendantAResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Demonstration.ServiceReference1.getDescendantAResponse> Demonstration.ServiceReference1.Service1Soap.getDescendantAAsync(Demonstration.ServiceReference1.getDescendantARequest request) {
            return base.Channel.getDescendantAAsync(request);
        }
        
        public System.Threading.Tasks.Task<Demonstration.ServiceReference1.getDescendantAResponse> getDescendantAAsync(string hosts) {
            Demonstration.ServiceReference1.getDescendantARequest inValue = new Demonstration.ServiceReference1.getDescendantARequest();
            inValue.Body = new Demonstration.ServiceReference1.getDescendantARequestBody();
            inValue.Body.hosts = hosts;
            return ((Demonstration.ServiceReference1.Service1Soap)(this)).getDescendantAAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Demonstration.ServiceReference1.getDescendantResponse Demonstration.ServiceReference1.Service1Soap.getDescendant(Demonstration.ServiceReference1.getDescendantRequest request) {
            return base.Channel.getDescendant(request);
        }
        
        public string getDescendant(string hosts) {
            Demonstration.ServiceReference1.getDescendantRequest inValue = new Demonstration.ServiceReference1.getDescendantRequest();
            inValue.Body = new Demonstration.ServiceReference1.getDescendantRequestBody();
            inValue.Body.hosts = hosts;
            Demonstration.ServiceReference1.getDescendantResponse retVal = ((Demonstration.ServiceReference1.Service1Soap)(this)).getDescendant(inValue);
            return retVal.Body.getDescendantResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Demonstration.ServiceReference1.getDescendantResponse> Demonstration.ServiceReference1.Service1Soap.getDescendantAsync(Demonstration.ServiceReference1.getDescendantRequest request) {
            return base.Channel.getDescendantAsync(request);
        }
        
        public System.Threading.Tasks.Task<Demonstration.ServiceReference1.getDescendantResponse> getDescendantAsync(string hosts) {
            Demonstration.ServiceReference1.getDescendantRequest inValue = new Demonstration.ServiceReference1.getDescendantRequest();
            inValue.Body = new Demonstration.ServiceReference1.getDescendantRequestBody();
            inValue.Body.hosts = hosts;
            return ((Demonstration.ServiceReference1.Service1Soap)(this)).getDescendantAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Demonstration.ServiceReference1.getLocationResponse Demonstration.ServiceReference1.Service1Soap.getLocation(Demonstration.ServiceReference1.getLocationRequest request) {
            return base.Channel.getLocation(request);
        }
        
        public string getLocation(string locs, int intLoc) {
            Demonstration.ServiceReference1.getLocationRequest inValue = new Demonstration.ServiceReference1.getLocationRequest();
            inValue.Body = new Demonstration.ServiceReference1.getLocationRequestBody();
            inValue.Body.locs = locs;
            inValue.Body.intLoc = intLoc;
            Demonstration.ServiceReference1.getLocationResponse retVal = ((Demonstration.ServiceReference1.Service1Soap)(this)).getLocation(inValue);
            return retVal.Body.getLocationResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Demonstration.ServiceReference1.getLocationResponse> Demonstration.ServiceReference1.Service1Soap.getLocationAsync(Demonstration.ServiceReference1.getLocationRequest request) {
            return base.Channel.getLocationAsync(request);
        }
        
        public System.Threading.Tasks.Task<Demonstration.ServiceReference1.getLocationResponse> getLocationAsync(string locs, int intLoc) {
            Demonstration.ServiceReference1.getLocationRequest inValue = new Demonstration.ServiceReference1.getLocationRequest();
            inValue.Body = new Demonstration.ServiceReference1.getLocationRequestBody();
            inValue.Body.locs = locs;
            inValue.Body.intLoc = intLoc;
            return ((Demonstration.ServiceReference1.Service1Soap)(this)).getLocationAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Demonstration.ServiceReference1.runBeast_Response Demonstration.ServiceReference1.Service1Soap.runBeast_(Demonstration.ServiceReference1.runBeast_Request request) {
            return base.Channel.runBeast_(request);
        }
        
        public string runBeast_(string Email, string newDir0) {
            Demonstration.ServiceReference1.runBeast_Request inValue = new Demonstration.ServiceReference1.runBeast_Request();
            inValue.Body = new Demonstration.ServiceReference1.runBeast_RequestBody();
            inValue.Body.Email = Email;
            inValue.Body.newDir0 = newDir0;
            Demonstration.ServiceReference1.runBeast_Response retVal = ((Demonstration.ServiceReference1.Service1Soap)(this)).runBeast_(inValue);
            return retVal.Body.runBeast_Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Demonstration.ServiceReference1.runBeast_Response> Demonstration.ServiceReference1.Service1Soap.runBeast_Async(Demonstration.ServiceReference1.runBeast_Request request) {
            return base.Channel.runBeast_Async(request);
        }
        
        public System.Threading.Tasks.Task<Demonstration.ServiceReference1.runBeast_Response> runBeast_Async(string Email, string newDir0) {
            Demonstration.ServiceReference1.runBeast_Request inValue = new Demonstration.ServiceReference1.runBeast_Request();
            inValue.Body = new Demonstration.ServiceReference1.runBeast_RequestBody();
            inValue.Body.Email = Email;
            inValue.Body.newDir0 = newDir0;
            return ((Demonstration.ServiceReference1.Service1Soap)(this)).runBeast_Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Demonstration.ServiceReference1.LogCompResponse Demonstration.ServiceReference1.Service1Soap.LogComp(Demonstration.ServiceReference1.LogCompRequest request) {
            return base.Channel.LogComp(request);
        }
        
        public string LogComp(string JobId, string eMail, string Status, string CompuType, string SearchCR) {
            Demonstration.ServiceReference1.LogCompRequest inValue = new Demonstration.ServiceReference1.LogCompRequest();
            inValue.Body = new Demonstration.ServiceReference1.LogCompRequestBody();
            inValue.Body.JobId = JobId;
            inValue.Body.eMail = eMail;
            inValue.Body.Status = Status;
            inValue.Body.CompuType = CompuType;
            inValue.Body.SearchCR = SearchCR;
            Demonstration.ServiceReference1.LogCompResponse retVal = ((Demonstration.ServiceReference1.Service1Soap)(this)).LogComp(inValue);
            return retVal.Body.LogCompResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Demonstration.ServiceReference1.LogCompResponse> Demonstration.ServiceReference1.Service1Soap.LogCompAsync(Demonstration.ServiceReference1.LogCompRequest request) {
            return base.Channel.LogCompAsync(request);
        }
        
        public System.Threading.Tasks.Task<Demonstration.ServiceReference1.LogCompResponse> LogCompAsync(string JobId, string eMail, string Status, string CompuType, string SearchCR) {
            Demonstration.ServiceReference1.LogCompRequest inValue = new Demonstration.ServiceReference1.LogCompRequest();
            inValue.Body = new Demonstration.ServiceReference1.LogCompRequestBody();
            inValue.Body.JobId = JobId;
            inValue.Body.eMail = eMail;
            inValue.Body.Status = Status;
            inValue.Body.CompuType = CompuType;
            inValue.Body.SearchCR = SearchCR;
            return ((Demonstration.ServiceReference1.Service1Soap)(this)).LogCompAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Demonstration.ServiceReference1.ownSequences_runZooPhyResponse Demonstration.ServiceReference1.Service1Soap.ownSequences_runZooPhy(Demonstration.ServiceReference1.ownSequences_runZooPhyRequest request) {
            return base.Channel.ownSequences_runZooPhy(request);
        }
        
        public string ownSequences_runZooPhy(string Email, string strInputFasta, string sModel, string UserSpcdId, string mcmc, string logfr) {
            Demonstration.ServiceReference1.ownSequences_runZooPhyRequest inValue = new Demonstration.ServiceReference1.ownSequences_runZooPhyRequest();
            inValue.Body = new Demonstration.ServiceReference1.ownSequences_runZooPhyRequestBody();
            inValue.Body.Email = Email;
            inValue.Body.strInputFasta = strInputFasta;
            inValue.Body.sModel = sModel;
            inValue.Body.UserSpcdId = UserSpcdId;
            inValue.Body.mcmc = mcmc;
            inValue.Body.logfr = logfr;
            Demonstration.ServiceReference1.ownSequences_runZooPhyResponse retVal = ((Demonstration.ServiceReference1.Service1Soap)(this)).ownSequences_runZooPhy(inValue);
            return retVal.Body.ownSequences_runZooPhyResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Demonstration.ServiceReference1.ownSequences_runZooPhyResponse> Demonstration.ServiceReference1.Service1Soap.ownSequences_runZooPhyAsync(Demonstration.ServiceReference1.ownSequences_runZooPhyRequest request) {
            return base.Channel.ownSequences_runZooPhyAsync(request);
        }
        
        public System.Threading.Tasks.Task<Demonstration.ServiceReference1.ownSequences_runZooPhyResponse> ownSequences_runZooPhyAsync(string Email, string strInputFasta, string sModel, string UserSpcdId, string mcmc, string logfr) {
            Demonstration.ServiceReference1.ownSequences_runZooPhyRequest inValue = new Demonstration.ServiceReference1.ownSequences_runZooPhyRequest();
            inValue.Body = new Demonstration.ServiceReference1.ownSequences_runZooPhyRequestBody();
            inValue.Body.Email = Email;
            inValue.Body.strInputFasta = strInputFasta;
            inValue.Body.sModel = sModel;
            inValue.Body.UserSpcdId = UserSpcdId;
            inValue.Body.mcmc = mcmc;
            inValue.Body.logfr = logfr;
            return ((Demonstration.ServiceReference1.Service1Soap)(this)).ownSequences_runZooPhyAsync(inValue);
        }
    }
}
